name: Android Library Coverage Example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage-espresso:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run lib's JUnit TEST
      run: |
        cd Android-Project
        ./gradlew lib:testDebugUnitTest

    - name: Run lib's Espresso TEST
      uses: ReactiveCircus/android-emulator-runner@v2.4.0
      with:
        api-level: 29
        script: ./emulator-lib.sh

    - name: Run app's JUnit TEST
      run: |
        cd Android-Project
        ./gradlew sampleapp:testDebugUnitTest

    - name: Run app's Espresso TEST
      uses: ReactiveCircus/android-emulator-runner@v2.4.0
      with:
        api-level: 29
        script: ./emulator.sh

    - name: Upload coverage report
      run: |
        cd Android-Project
        ./gradlew jacocoMergedReport
        bash <(curl -s https://codecov.io/bash) -f ./lib/build/reports/jacoco/jacocoMergedReport/jacocoMergedReport.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
