name: Android Library Coverage Example

on: [push, pull_request]

jobs:
  coverage-junit:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run JUnit TEST
      run: |
        cd Android-Project
        ./gradlew lib:testDebugUnitTest

    - name: Upload coverage report
      run: |
        cd Android-Project
        ./gradlew jacocoMergedReport
        bash <(curl -s https://codecov.io/bash) -f ./lib/build/reports/jacoco/jacocoMergedReport/jacocoMergedReport.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
